name: flutter_hw_lototinder
description: Flutter project for hw number 1
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.2.0
  flutter_localizations:
    sdk: flutter
  intl: any
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true
  
  assets:
    - assets/icons/dislike.svg
    - assets/icons/like.svg
    - assets/icons/dislike.png
    - assets/icons/like.png
    - assets/icons/cat.png
    - assets/icons/girl.png
    - assets/icons/boy.png
    - assets/Kototinder_icon.png

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Kototinder_icon.png"
