// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'src/data/image_info_item_entity.dart';
import 'src/data/likes_history_item_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 7691268481354856948),
      name: 'ImageInfoItemEntity',
      lastPropertyId: const obx_int.IdUid(5, 8540511649516030524),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 8429859692799898352),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3783794103161416372),
            name: 'apiSourceID',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3925802604291516562),
            name: 'url',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(2, 2717195133478146980)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3544987833213303903),
            name: 'imageName',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 8540511649516030524),
            name: 'extraInfoMap',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 8790852094190136273),
      name: 'LikesHistoryItemEntity',
      lastPropertyId: const obx_int.IdUid(4, 882528390767281548),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 6681430632353259525),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3033082172979514996),
            name: 'imageInfoId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(1, 5005350882515269499),
            relationTarget: 'ImageInfoItemEntity'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3969616646277635113),
            name: 'actionTime',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 882528390767281548),
            name: 'isLike',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(2, 8790852094190136273),
      lastIndexId: const obx_int.IdUid(2, 2717195133478146980),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    ImageInfoItemEntity: obx_int.EntityDefinition<ImageInfoItemEntity>(
        model: _entities[0],
        toOneRelations: (ImageInfoItemEntity object) => [],
        toManyRelations: (ImageInfoItemEntity object) => {},
        getId: (ImageInfoItemEntity object) => object.id,
        setId: (ImageInfoItemEntity object, int id) {
          object.id = id;
        },
        objectToFB: (ImageInfoItemEntity object, fb.Builder fbb) {
          final urlOffset = fbb.writeString(object.url);
          final imageNameOffset = fbb.writeString(object.imageName);
          final extraInfoMapOffset = fbb.writeString(object.extraInfoMap);
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.apiSourceID);
          fbb.addOffset(2, urlOffset);
          fbb.addOffset(3, imageNameOffset);
          fbb.addOffset(4, extraInfoMapOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final apiSourceIDParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final urlParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final imageNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final extraInfoMapParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, '');
          final object = ImageInfoItemEntity(
              id: idParam,
              apiSourceID: apiSourceIDParam,
              url: urlParam,
              imageName: imageNameParam,
              extraInfoMap: extraInfoMapParam);

          return object;
        }),
    LikesHistoryItemEntity: obx_int.EntityDefinition<LikesHistoryItemEntity>(
        model: _entities[1],
        toOneRelations: (LikesHistoryItemEntity object) => [object.imageInfo],
        toManyRelations: (LikesHistoryItemEntity object) => {},
        getId: (LikesHistoryItemEntity object) => object.id,
        setId: (LikesHistoryItemEntity object, int id) {
          object.id = id;
        },
        objectToFB: (LikesHistoryItemEntity object, fb.Builder fbb) {
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.imageInfo.targetId);
          fbb.addInt64(2, object.actionTime.millisecondsSinceEpoch);
          fbb.addBool(3, object.isLike);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final actionTimeParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0));
          final isLikeParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 10, false);
          final object = LikesHistoryItemEntity(
              id: idParam, actionTime: actionTimeParam, isLike: isLikeParam);
          object.imageInfo.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          object.imageInfo.attach(store);
          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ImageInfoItemEntity] entity fields to define ObjectBox queries.
class ImageInfoItemEntity_ {
  /// See [ImageInfoItemEntity.id].
  static final id =
      obx.QueryIntegerProperty<ImageInfoItemEntity>(_entities[0].properties[0]);

  /// See [ImageInfoItemEntity.apiSourceID].
  static final apiSourceID =
      obx.QueryIntegerProperty<ImageInfoItemEntity>(_entities[0].properties[1]);

  /// See [ImageInfoItemEntity.url].
  static final url =
      obx.QueryStringProperty<ImageInfoItemEntity>(_entities[0].properties[2]);

  /// See [ImageInfoItemEntity.imageName].
  static final imageName =
      obx.QueryStringProperty<ImageInfoItemEntity>(_entities[0].properties[3]);

  /// See [ImageInfoItemEntity.extraInfoMap].
  static final extraInfoMap =
      obx.QueryStringProperty<ImageInfoItemEntity>(_entities[0].properties[4]);
}

/// [LikesHistoryItemEntity] entity fields to define ObjectBox queries.
class LikesHistoryItemEntity_ {
  /// See [LikesHistoryItemEntity.id].
  static final id = obx.QueryIntegerProperty<LikesHistoryItemEntity>(
      _entities[1].properties[0]);

  /// See [LikesHistoryItemEntity.imageInfo].
  static final imageInfo =
      obx.QueryRelationToOne<LikesHistoryItemEntity, ImageInfoItemEntity>(
          _entities[1].properties[1]);

  /// See [LikesHistoryItemEntity.actionTime].
  static final actionTime =
      obx.QueryDateProperty<LikesHistoryItemEntity>(_entities[1].properties[2]);

  /// See [LikesHistoryItemEntity.isLike].
  static final isLike = obx.QueryBooleanProperty<LikesHistoryItemEntity>(
      _entities[1].properties[3]);
}
